{% set version = "0.2.2" %}

package:
  name: cdsswarm
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/cdsswarm/cdsswarm-{{ version }}.tar.gz
  sha256: 993dc350d8a72d1ebac9fb813c48ac5af5dc50c6c06d230fa466e89362fdff33

build:
  noarch: python
  entry_points:
    - cdsswarm = cdsswarm.cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - cdsapi >=0.7
    - requests
    - tqdm
    - textual >=0.87
    - tomli >=1.1.0
    - shtab >=1.7

test:
  imports:
    - cdsswarm
  commands:
    - pip check
    - cdsswarm --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bgiebl/cdsswarm
  summary: Concurrent CDS API downloader with TUI and script mode
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bgiebl
